/* Generated by Yosys 0.33+112 (git sha1 3e02b63ee, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module dff(clk, rst, d, q);
  wire _0_;
  input clk;
  wire clk;
  input d;
  wire d;
  output q;
  wire q;
  input rst;
  wire rst;
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1_ (
    .A(d),
    .SLEEP(rst),
    .X(_0_)
  );
  sky130_fd_sc_hd__dfxtp_1 _2_ (
    .CLK(clk),
    .D(_0_),
    .Q(q)
  );
endmodule
