/* Generated by Yosys 0.33+112 (git sha1 3e02b63ee, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module counter(clk, rst, q);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  input clk;
  wire clk;
  output [3:0] q;
  wire [3:0] q;
  input rst;
  wire rst;
  sky130_fd_sc_hd__nor2_1 _08_ (
    .A(q[0]),
    .B(rst),
    .Y(_00_)
  );
  sky130_fd_sc_hd__o21bai_1 _09_ (
    .A1(q[0]),
    .A2(q[1]),
    .B1_N(rst),
    .Y(_04_)
  );
  sky130_fd_sc_hd__a21oi_1 _10_ (
    .A1(q[0]),
    .A2(q[1]),
    .B1(_04_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__and3_1 _11_ (
    .A(q[0]),
    .B(q[1]),
    .C(q[2]),
    .X(_05_)
  );
  sky130_fd_sc_hd__a21oi_1 _12_ (
    .A1(q[0]),
    .A2(q[1]),
    .B1(q[2]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__nor3_1 _13_ (
    .A(rst),
    .B(_05_),
    .C(_06_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__a41oi_1 _14_ (
    .A1(q[0]),
    .A2(q[1]),
    .A3(q[2]),
    .A4(q[3]),
    .B1(rst),
    .Y(_07_)
  );
  sky130_fd_sc_hd__o21a_1 _15_ (
    .A1(q[3]),
    .A2(_05_),
    .B1(_07_),
    .X(_03_)
  );
  sky130_fd_sc_hd__dfxtp_1 _16_ (
    .CLK(clk),
    .D(_00_),
    .Q(q[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _17_ (
    .CLK(clk),
    .D(_01_),
    .Q(q[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _18_ (
    .CLK(clk),
    .D(_02_),
    .Q(q[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _19_ (
    .CLK(clk),
    .D(_03_),
    .Q(q[3])
  );
endmodule
