/* Generated by Yosys 0.33+112 (git sha1 3e02b63ee, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module alu(a, b, opcode, result);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  input [2:0] opcode;
  wire [2:0] opcode;
  output [3:0] result;
  wire [3:0] result;
  sky130_fd_sc_hd__nor2_1 _079_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nor2_1 _080_ (
    .A(opcode[1]),
    .B(opcode[0]),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nand2_1 _081_ (
    .A(opcode[2]),
    .B(_001_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nand2_1 _082_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nor3b_1 _083_ (
    .A(opcode[0]),
    .B(opcode[2]),
    .C_N(opcode[1]),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nand3b_1 _084_ (
    .A_N(opcode[2]),
    .B(opcode[0]),
    .C(opcode[1]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nor2_1 _085_ (
    .A(opcode[1]),
    .B(opcode[2]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__and3_1 _086_ (
    .A(opcode[1]),
    .B(opcode[0]),
    .C(opcode[2]),
    .X(_007_)
  );
  sky130_fd_sc_hd__nand3_1 _087_ (
    .A(opcode[1]),
    .B(opcode[0]),
    .C(opcode[2]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__o21ai_0 _088_ (
    .A1(_006_),
    .A2(_007_),
    .B1(_003_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__a21oi_1 _089_ (
    .A1(_002_),
    .A2(_009_),
    .B1(_000_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nand3b_1 _090_ (
    .A_N(opcode[1]),
    .B(opcode[0]),
    .C(opcode[2]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__a21oi_1 _091_ (
    .A1(a[0]),
    .A2(b[0]),
    .B1(_011_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nor3b_1 _092_ (
    .A(opcode[2]),
    .B(_003_),
    .C_N(opcode[1]),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nand3b_1 _093_ (
    .A_N(opcode[0]),
    .B(opcode[2]),
    .C(opcode[1]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nor3_1 _094_ (
    .A(a[0]),
    .B(b[0]),
    .C(_014_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__or4_1 _095_ (
    .A(_010_),
    .B(_012_),
    .C(_013_),
    .D(_015_),
    .X(result[0])
  );
  sky130_fd_sc_hd__nand2b_1 _096_ (
    .A_N(a[0]),
    .B(b[0]),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nor3b_1 _097_ (
    .A(opcode[1]),
    .B(opcode[2]),
    .C_N(opcode[0]),
    .Y(_017_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _098_ (
    .A(b[0]),
    .SLEEP(_017_),
    .X(_018_)
  );
  sky130_fd_sc_hd__xnor2_1 _099_ (
    .A(b[1]),
    .B(_018_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__xor2_1 _100_ (
    .A(a[1]),
    .B(_019_),
    .X(_020_)
  );
  sky130_fd_sc_hd__o21ai_0 _101_ (
    .A1(_016_),
    .A2(_020_),
    .B1(_006_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__a21o_1 _102_ (
    .A1(_016_),
    .A2(_020_),
    .B1(_021_),
    .X(_022_)
  );
  sky130_fd_sc_hd__nand2_1 _103_ (
    .A(b[1]),
    .B(a[1]),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nor2_1 _104_ (
    .A(b[1]),
    .B(a[1]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__o21ai_0 _105_ (
    .A1(b[1]),
    .A2(a[1]),
    .B1(_007_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__a21boi_0 _106_ (
    .A1(_011_),
    .A2(_025_),
    .B1_N(_023_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__a22o_1 _107_ (
    .A1(a[0]),
    .A2(b[1]),
    .B1(a[1]),
    .B2(b[0]),
    .X(_027_)
  );
  sky130_fd_sc_hd__nand4_1 _108_ (
    .A(a[0]),
    .B(b[0]),
    .C(b[1]),
    .D(a[1]),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand3_1 _109_ (
    .A(_004_),
    .B(_027_),
    .C(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__o22ai_1 _110_ (
    .A1(_005_),
    .A2(_023_),
    .B1(_024_),
    .B2(_002_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nor3_1 _111_ (
    .A(b[1]),
    .B(a[1]),
    .C(_014_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nor3_1 _112_ (
    .A(_026_),
    .B(_030_),
    .C(_031_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand3_1 _113_ (
    .A(_022_),
    .B(_029_),
    .C(_032_),
    .Y(result[1])
  );
  sky130_fd_sc_hd__maj3_1 _114_ (
    .A(a[1]),
    .B(_016_),
    .C(_019_),
    .X(_033_)
  );
  sky130_fd_sc_hd__nor2_1 _115_ (
    .A(b[0]),
    .B(b[1]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nor2_1 _116_ (
    .A(_017_),
    .B(_034_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nor2_1 _117_ (
    .A(b[2]),
    .B(_035_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__xnor2_1 _118_ (
    .A(b[2]),
    .B(_035_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__xnor2_1 _119_ (
    .A(a[2]),
    .B(_037_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__xnor2_1 _120_ (
    .A(_033_),
    .B(_038_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand2_1 _121_ (
    .A(_006_),
    .B(_039_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand2_1 _122_ (
    .A(a[0]),
    .B(b[2]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nand2_1 _123_ (
    .A(b[1]),
    .B(a[2]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nand4_1 _124_ (
    .A(b[0]),
    .B(b[1]),
    .C(a[1]),
    .D(a[2]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__a22oi_1 _125_ (
    .A1(b[1]),
    .A2(a[1]),
    .B1(a[2]),
    .B2(b[0]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _126_ (
    .A(_043_),
    .SLEEP(_044_),
    .X(_045_)
  );
  sky130_fd_sc_hd__nor2b_1 _127_ (
    .A(_041_),
    .B_N(_045_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__a21oi_1 _128_ (
    .A1(a[0]),
    .A2(b[2]),
    .B1(_045_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__o21ai_0 _129_ (
    .A1(_046_),
    .A2(_047_),
    .B1(_028_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nor3_1 _130_ (
    .A(_028_),
    .B(_046_),
    .C(_047_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand2_1 _131_ (
    .A(_004_),
    .B(_048_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nand2_1 _132_ (
    .A(b[2]),
    .B(a[2]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nor2_1 _133_ (
    .A(b[2]),
    .B(a[2]),
    .Y(_052_)
  );
  sky130_fd_sc_hd__o21a_1 _134_ (
    .A1(_008_),
    .A2(_052_),
    .B1(_011_),
    .X(_053_)
  );
  sky130_fd_sc_hd__a21oi_1 _135_ (
    .A1(b[2]),
    .A2(a[2]),
    .B1(_053_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nor3_1 _136_ (
    .A(b[2]),
    .B(a[2]),
    .C(_014_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__o22ai_1 _137_ (
    .A1(_005_),
    .A2(_051_),
    .B1(_052_),
    .B2(_002_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nor3_1 _138_ (
    .A(_054_),
    .B(_055_),
    .C(_056_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__o211ai_1 _139_ (
    .A1(_049_),
    .A2(_050_),
    .B1(_057_),
    .C1(_040_),
    .Y(result[2])
  );
  sky130_fd_sc_hd__maj3_1 _140_ (
    .A(a[2]),
    .B(_033_),
    .C(_037_),
    .X(_058_)
  );
  sky130_fd_sc_hd__nand2_1 _141_ (
    .A(b[3]),
    .B(a[3]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nor2_1 _142_ (
    .A(b[3]),
    .B(a[3]),
    .Y(_060_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _143_ (
    .A(_059_),
    .SLEEP(_060_),
    .X(_061_)
  );
  sky130_fd_sc_hd__nor2_1 _144_ (
    .A(_017_),
    .B(_036_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__xnor2_1 _145_ (
    .A(_061_),
    .B(_062_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__xnor2_1 _146_ (
    .A(_058_),
    .B(_063_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__o21ai_0 _147_ (
    .A1(_041_),
    .A2(_044_),
    .B1(_043_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand2_1 _148_ (
    .A(a[0]),
    .B(b[3]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand2_1 _149_ (
    .A(a[1]),
    .B(b[2]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__xnor2_1 _150_ (
    .A(_066_),
    .B(_067_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand2_1 _151_ (
    .A(b[0]),
    .B(a[3]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__xor2_1 _152_ (
    .A(_042_),
    .B(_069_),
    .X(_070_)
  );
  sky130_fd_sc_hd__xnor2_1 _153_ (
    .A(_068_),
    .B(_070_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__xnor2_1 _154_ (
    .A(_065_),
    .B(_071_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__xnor2_1 _155_ (
    .A(_049_),
    .B(_072_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nand2_1 _156_ (
    .A(_004_),
    .B(_073_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__o21ai_0 _157_ (
    .A1(_008_),
    .A2(_060_),
    .B1(_011_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nand2b_1 _158_ (
    .A_N(_014_),
    .B(_060_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__o221ai_1 _159_ (
    .A1(_005_),
    .A2(_059_),
    .B1(_060_),
    .B2(_002_),
    .C1(_076_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__a21oi_1 _160_ (
    .A1(_059_),
    .A2(_075_),
    .B1(_077_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__o311ai_0 _161_ (
    .A1(opcode[1]),
    .A2(opcode[2]),
    .A3(_064_),
    .B1(_074_),
    .C1(_078_),
    .Y(result[3])
  );
endmodule
